language: ruby
rvm:
  - "2.6.6"
services:
  - postgresql
before_install:
  - gem install bundler
script:
  - bundle install --jobs=3 --retry=3
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
