version: "3"

services:
  db:
    image: "postgres:12.2-alpine"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  web:
    depends_on:
      - "db"
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ".env"

volumes:
  postgres:
